---
name: prod-ocf-victorialogs

releases:
- name: victorialogs
  version: latest
- name: bpm
  version: latest

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-600000

instance_groups:
# VLStorage - Persistent storage node
- name: vlstorage
  instances: 1
  azs:
  - prod-ocf-z2
  networks:
  - name: prod-ocf.victorialogs.net-victorialogs
    static_ips:
    - 10.4.8.32
  vm_type: prod-ocf.victorialogs.vm-gpu-small
  stemcell: default
  persistent_disk_type: prod-ocf.victorialogs.disk-victorialogs

  jobs:
  - name: bpm
    release: bpm

  - name: vlstorage
    release: victorialogs
    provides:
      vlstorage:
        as: vlstorage
        shared: true
    properties:
      vlstorage:
        # Network Configuration
        http_port: 9491

        # Storage Configuration
        storage_path: "/var/vcap/store/vlstorage/data"
        retention_period: "7d"  # 7 days
        future_retention: "2d"

        # Performance Tuning
        max_concurrent_inserts: 32
        insert_max_queue_duration: "1m"
        search_max_concurrent_requests: 16
        search_max_queue_duration: "10s"

        # Memory Configuration
        memory_allowed_percent: 60

        # Cache Configuration
        cache_expire_duration: "30m"
        prev_cache_removal_percent: 0.1
        blockcache_misses_before_caching: 2

        # Disk Space Management
        storage_min_free_disk_space_bytes: "10000000"
        inmemory_data_flush_interval: "5s"

        # Search Configuration
        search_max_tag_keys: 100000
        search_max_tag_values: 100000
        search_max_tag_value_suffixes_per_search: 100000

        # HTTP Server Configuration
        http_conn_timeout: "2m"
        http_idle_conn_timeout: "1m"
        http_max_graceful_shutdown_duration: "7s"

        # Logging Configuration
        log_level: "INFO"
        log_format: "default"
        logger_output: "stderr"
        logger_timezone: "UTC"
        logger_max_arg_len: 5000

        # Authentication (leave empty for no auth)
        http_auth_username: ""
        http_auth_password: ""

          #- name: monitoring
          #  release: victorialogs
          #  properties:
          #    monitoring:
          #      enabled: true
          #      node_exporter_port: 9100
          #      scrape_interval: 30s
          #      retention_days: 7

# VLInsert - Log ingestion node
- name: vlinsert
  instances: 1
  azs:
  - prod-ocf-z2
  networks:
  - name: prod-ocf.victorialogs.net-victorialogs
    static_ips:
    - 10.4.8.33
  vm_type: prod-ocf.victorialogs.vm-gpu-small
  stemcell: default
  persistent_disk_type: prod-ocf.victorialogs.disk-victorialogs

  jobs:
  - name: bpm
    release: bpm

  - name: vlinsert
    release: victorialogs
    consumes:
      vlstorage:
        from: vlstorage

        deployment: prod-ocf-victorialogs
    provides:
      vlinsert:
        as: vlinsert
        shared: true
    properties:
      vlinsert:
        # Core HTTP settings
        http_port: 9481
        http_conn_timeout: "2m0s"
        http_idle_conn_timeout: "1m0s"
        http_max_graceful_shutdown_duration: "7s"

        # Core insert settings
        max_concurrent_inserts: 32
        insert_max_queue_duration: "1m"
        insert_max_line_size_bytes: 262144
        insert_max_fields_per_line: 1000
        insert_max_request_size: 67108864

        # Insert concurrency settings
        insert_concurrency: 2
        insert_disable_compression: false

        # Memory and cache settings
        memory_allowed_percent: 60
        cache_expire_duration: "30m0s"
        prev_cache_removal_percent: 0.1
        blockcache_misses_before_caching: 2

        # String interning settings
        intern_string_max_len: 500
        intern_string_cache_expire_duration: "6m0s"
        intern_string_disable_cache: false

        # Log ingestion settings
        log_ingested_rows: false
        log_new_streams: false
        default_msg_value: "missing _msg field"

        # Logging settings
        logger_level: "INFO"
        logger_format: "default"
        logger_output: "stderr"
        logger_timezone: "UTC"
        logger_max_arg_len: 5000
        logger_disable_timestamps: false

        # Metrics exposure
        metrics_expose_metadata: false

        # Query tracing
        deny_query_tracing: false

        # Environment flags
        envflag_enable: false

        # IPv6
        enable_tcp6: false

        # File system settings
        fs_disable_mmap: false
        filestream_disable_fadvise: false

        # Authentication (leave empty for no auth)
        http_auth_username: ""
        http_auth_password: ""

          #- name: monitoring
          #  release: victorialogs
          #  properties:
          #    monitoring:
          #      enabled: true
          #      node_exporter_port: 9100
          #      scrape_interval: 30s
          #      retention_days: 7

# VLSelect - Query processing node
- name: vlselect
  instances: 1
  azs:
  - prod-ocf-z2
  networks:
  - name: prod-ocf.victorialogs.net-victorialogs
    static_ips:
    - 10.4.8.34
  vm_type: prod-ocf.victorialogs.vm-gpu-small
  stemcell: default
  persistent_disk_type: prod-ocf.victorialogs.disk-victorialogs

  jobs:
  - name: bpm
    release: bpm

  - name: vlselect
    release: victorialogs
    consumes:
      vlstorage:
        from: vlstorage
        deployment: prod-ocf-victorialogs

    provides:
      vlselect:
        as: vlselect
        shared: true
    properties:
      vlselect:
        # Core HTTP settings
        http_port: 9471
        http_conn_timeout: "2m0s"
        http_idle_conn_timeout: "1m0s"
        http_max_graceful_shutdown_duration: "7s"

        # Select concurrency settings
        select_disable_compression: false

        # Memory and cache settings
        memory_allowed_percent: 60
        cache_expire_duration: "30m0s"
        prev_cache_removal_percent: 0.1
        blockcache_misses_before_caching: 2

        # String interning settings
        intern_string_max_len: 500
        intern_string_cache_expire_duration: "6m0s"
        intern_string_disable_cache: false

        # Search/query settings
        search_allow_partial_response: false
        default_parallel_readers: 32

        # Query limits
        search_max_concurrent_requests: 16
        search_max_queue_duration: "10s"
        search_max_query_duration: "30s"

        # Query tracing
        deny_query_tracing: false

        # Logging settings
        logger_level: "INFO"
        logger_format: "default"
        logger_output: "stderr"
        logger_timezone: "UTC"
        logger_max_arg_len: 5000
        logger_disable_timestamps: false

        # Metrics exposure
        metrics_expose_metadata: false

        # Environment flags
        envflag_enable: false

        # IPv6
        enable_tcp6: false

        # File system settings
        fs_disable_mmap: false
        filestream_disable_fadvise: false

        # Authentication (leave empty for no auth)
        http_auth_username: ""
        http_auth_password: ""

          #- name: monitoring
          #  release: victorialogs
          #  properties:
          #    monitoring:
          #      enabled: true
          #      node_exporter_port: 9100
          #      scrape_interval: 30s
          #      retention_days: 7
          # default: victorialogs-cluster
